-- EcoRevive Supabase Database Schema
-- Run this script in your Supabase SQL Editor to create all necessary tables and relations.

-- 1. Create users table (linked to auth.users)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT,
    email TEXT,
    city TEXT,
    lang_pref TEXT DEFAULT 'en',
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on users table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to profiles" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow individual write access to profiles" ON public.users FOR ALL USING (auth.uid() = id);

-- 2. Create devices table
CREATE TABLE IF NOT EXISTS public.devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    type TEXT,
    brand TEXT,
    photo_url TEXT,
    scan_result JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on devices
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to manage their own scanned devices" ON public.devices FOR ALL USING (auth.uid() = user_id);

-- 3. Create components table
CREATE TABLE IF NOT EXISTS public.components (
    id TEXT PRIMARY KEY,
    device_id BIGINT REFERENCES public.devices(id) ON DELETE SET NULL,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    hindi_name TEXT,
    grade TEXT DEFAULT 'A',
    reuse_potential TEXT DEFAULT 'Medium',
    safety_risk TEXT DEFAULT 'Safe',
    estimated_value_inr INTEGER DEFAULT 0,
    image_url TEXT,
    status TEXT DEFAULT 'in_inventory',
    safety_note TEXT,
    removal_difficulty TEXT DEFAULT 'Medium',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on components
ALTER TABLE public.components ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read for components" ON public.components FOR SELECT USING (true);
CREATE POLICY "Allow user write for own components" ON public.components FOR ALL USING (auth.uid() = user_id);

-- 4. Create listings table
CREATE TABLE IF NOT EXISTS public.listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id TEXT REFERENCES public.components(id) ON DELETE CASCADE NOT NULL,
    seller_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    price_inr INTEGER DEFAULT 0,
    listing_type TEXT DEFAULT 'sell',
    description TEXT,
    city TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on listings
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read for active listings" ON public.listings FOR SELECT USING (true);
CREATE POLICY "Allow users to manage own listings" ON public.listings FOR ALL USING (auth.uid() = seller_id);

-- 5. Create impact table
CREATE TABLE IF NOT EXISTS public.impact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
    components_recovered INTEGER DEFAULT 0,
    co2_saved_kg NUMERIC DEFAULT 0.0,
    landfill_diverted_kg NUMERIC DEFAULT 0.0,
    total_earnings_inr INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on impact
ALTER TABLE public.impact ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read of impact data" ON public.impact FOR SELECT USING (true);
CREATE POLICY "Allow user to update own impact data" ON public.impact FOR ALL USING (auth.uid() = user_id);

-- 6. Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    sender_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    receiver_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    message TEXT NOT NULL,
    read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on messages
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow user to view and write messages involving them" ON public.messages 
    FOR ALL USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- 7. Add Realtime Replication
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.listings;

-- 8. Create purchases table for purchase history
CREATE TABLE IF NOT EXISTS public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    listing_id BIGINT REFERENCES public.listings(id) ON DELETE CASCADE NOT NULL,
    razorpay_payment_id TEXT NOT NULL,
    razorpay_order_id TEXT NOT NULL,
    amount_inr INTEGER NOT NULL,
    status TEXT DEFAULT 'completed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on purchases
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to view own purchases" ON public.purchases FOR SELECT USING (auth.uid() = buyer_id);
CREATE POLICY "Allow users to insert own purchases" ON public.purchases FOR INSERT WITH CHECK (auth.uid() = buyer_id);
